#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.10
# In conjunction with Tcl version 8.6
#    Dec 05, 2021 05:54:07 AM
import sys
from pymata4 import pymata4
import time
try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import support_console as unknown_support
import soil as soil



def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Soil_Moisture_Detection (root)
    unknown_support.init(root, top)
    top.detect_moisture_level()
    root.mainloop()



w = None
def create_New_Toplevel_1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Soil_Moisture_Detection (w)
    unknown_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_New_Toplevel_1():
    global w
    w.destroy()
    w = None


class Soil_Moisture_Detection:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#d9d9d9' # X11 color: 'gray85'
        font9 = "-family {Segoe UI} -size 14 -weight bold -slant roman"  \
            " -underline 0 -overstrike 0"

        top.geometry("546x208+469+313")
        top.title("Soil Moisture Detection")
        top.configure(background="#d9d9d9")



        self.Label1 = Label(top)
        self.Label1.place(relx=0.2, rely=0.0, height=56, width=302)
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font9)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Moisture Level Detection''')
        self.Label1.configure(width=302)

        self.Label2 = Label(top)
        self.Label2.place(relx=0.2, rely=0.38, height=46, width=132)
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''Water Required?''')
        self.Label2.configure(width=132)

        self.Label3 = Label(top)
        self.Label3.place(relx=0.2, rely=0.67, height=36, width=122)
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(text='''Moisture Level''')
        self.Label3.configure(width=122)

        self.yn_lbl = Label(top)
        self.yn_lbl.place(relx=0.6, rely=0.43, height=26, width=76)
        self.yn_lbl.configure(background="#d9d9d9")
        self.yn_lbl.configure(disabledforeground="#a3a3a3")
        self.yn_lbl.configure(foreground="#000000")
        self.yn_lbl.configure(text='''No''')
        self.yn_lbl.configure(width=76)

        self.value_lbl = Label(top)
        self.value_lbl.place(relx=0.6, rely=0.72, height=26, width=74)
        self.value_lbl.configure(background="#d9d9d9")
        self.value_lbl.configure(disabledforeground="#a3a3a3")
        self.value_lbl.configure(foreground="#000000")
        self.value_lbl.configure(text='''0''')
        self.value_lbl.configure(width=74)

        global board
        global flag
        board, flag = self.set_board()


    def detect_moisture_level(self, analog_pin=1):
        global board
        global flag
        value, timestamp = board.analog_read(analog_pin)
        print(value, timestamp)
        value_percent = f"{str(round(value/1023 * 100))}%"
        self.value_lbl.config(text=value_percent)
        if ((value >= 1000) & (flag == False)):
            board.digital_write(13, 1)
            flag = True
            self.yn_lbl.config(text='No', background="green")
        if ((value < 1000) & (flag == True)):
            board.digital_write(13, 0)
            flag = False
            self.yn_lbl.config(text='Yes', background="red")
        time.sleep(1)
        self.value_lbl.after(400, self.detect_moisture_level)


    def set_board(self):
        board = pymata4.Pymata4()
        digital_pin = 13
        analog_pin = 1
        board.set_pin_mode_analog_input(analog_pin)
        board.set_pin_mode_digital_output(digital_pin)
        flag = False
        return board, flag

if __name__ == '__main__':
    vp_start_gui()


